# the action github-issues uses this file to actual label the pull requests
# the action checks WHAT changed and then the correct label is added
# only existing labels can be apllied, it cannot create new ones (do that in github)

bug:
  - '(?i)\b(bug|error|crash)\b'
enhancement:
  - '(?i)\b(feature|enhancement|idea)\b'
question:
  - '(?i)\b(question|how (do|to))\b'