<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bison.Core\Bison.Core.csproj" />
  </ItemGroup>
    
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
  <None Include="..\..\data\schema.sql" Link="data\schema.sql" CopyToOutputDirectory="PreserveNewest" />
  <None Include="..\..\data\dump.sql" Link="data\dump.sql" CopyToOutputDirectory="PreserveNewest" />
</ItemGroup>

</Project>
